### ISSUE TITLE
Value cannot be null

### ISSUE THREAD

**Issue by YHFoxes** [RumbleMike/ValorantStreamOverlay#19]
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.FromObject(Object o)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at ValorantStreamOverlay.RankDetection.RankParser(Int32 rankNumber) in C:\Users\Mike\source\repos\ValorantStreamOverlay\RankDetection.cs:line 73
   at ValorantStreamOverlay.RankDetection..ctor() in C:\Users\Mike\source\repos\ValorantStreamOverlay\RankDetection.cs:line 28
   at ValorantStreamOverlay.LogicHandler.pointTimer_Tick(Object sender, EventArgs e) in C:\Users\Mike\source\repos\ValorantStreamOverlay\LogicHandler.cs:line 362
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by souriscloud** [comment]
Hello, I am just trying to replicate method of this overlay, and it seems I cant get authorization done, since they've changed something.

@YHFoxes your issue should have to do with that. RIOT changed something and as response on authorization request arrives `{ type: "auth", error: "auth_failure", region: "" }` instead of proper response where accesstoken is gotten from.

@RumbleMike can you please take a look on that? I am not really sure where exactly did u captured thoose network frames to identificate request/response of authorization process to get accesstoken

**Comment by RumbleMike** [comment]
So far I see a lot of people getting this issue, I don't think it is on riots part. unless I am wrong, it seems to be on my API where all the ranks are located bugging out. I am adding more errors to the 1.0 release to find out. If it is an issue on riot part they added a rate limit that I have to figure out.
