### ISSUE TITLE
Value cannot be null. Parameter 'o'

### ISSUE THREAD

**Issue by ishaanmeena** [RumbleMike/ValorantStreamOverlay#64]
So, even after I set the correct region it fails to login and this error follows up.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null. (Parameter 'o')
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.FromObject(Object o)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at ValorantStreamOverlay.RankDetection.RankParser(Int32 rankNumber)
   at ValorantStreamOverlay.RankDetection..ctor()
   at ValorantStreamOverlay.LogicHandler.ReadSettings()
   at ValorantStreamOverlay.LogicHandler..ctor(ValorantOverStream instance)
   at ValorantStreamOverlay.ValorantOverStream.ValorantOverStream_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.20.51601
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.CoreLib.dll
----------------------------------------
ValorantStreamOverlay
    Assembly Version: 1.1.0.1
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/ishaa/AppData/Local/Temp/.net/ValorantStreamOverlay/xwzsafpx.eir/ValorantStreamOverlay.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.120.51303
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 4.0.2.1
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.Extensions.dll
----------------------------------------
System.Diagnostics.Debug
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.Debug.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.120.51303
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Resources.ResourceManager
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Resources.ResourceManager.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 4.0.15.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ComponentModel.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.NonGeneric.dll
----------------------------------------
System.Memory
    Assembly Version: 4.2.1.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Memory.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.20.21406
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/netstandard.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.ObjectModel.dll
----------------------------------------
System.Linq
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Linq.dll
----------------------------------------
System.Windows.Extensions
    Assembly Version: 4.0.1.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Windows.Extensions.dll
----------------------------------------
System.Buffers
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Buffers.dll
----------------------------------------
System.IO.FileSystem
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.IO.FileSystem.dll
----------------------------------------
AutoUpdater.NET
    Assembly Version: 1.6.4.0
    Win32 Version: 1.6.4.0
    CodeBase: file:///C:/Users/ishaa/AppData/Local/Temp/.net/ValorantStreamOverlay/xwzsafpx.eir/AutoUpdater.NET.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/mscorlib.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.800.120.51303
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.dll
----------------------------------------
System.Net.ServicePoint
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.Security.dll
----------------------------------------
System.Net.WebClient
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.WebClient.dll
----------------------------------------
System.Net.Requests
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.Requests.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Xml.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.Xml.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.Uri.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.Tracing.dll
----------------------------------------
System.Security.Principal
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Security.Principal.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.Http.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Text.RegularExpressions.dll
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Tasks.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Threading.Timer
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Timer.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly Version: 4.0.3.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.10/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.Diagnostics.Tools
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.Tools.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly Version: 4.3.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Net.NameResolution.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Xml.ReaderWriter.dll
----------------------------------------
System.Text.Encoding.Extensions
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 4.0.4.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Xml.XmlSerializer.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/ishaa/AppData/Local/Temp/.net/ValorantStreamOverlay/xwzsafpx.eir/Newtonsoft.Json.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Linq.Expressions.dll
----------------------------------------
RestSharp
    Assembly Version: 106.11.7.0
    Win32 Version: 106.11.7
    CodeBase: file:///C:/Users/ishaa/AppData/Local/Temp/.net/ValorantStreamOverlay/xwzsafpx.eir/RestSharp.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.5.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/Microsoft.CSharp.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 4.2.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Web.HttpUtility
    Assembly Version: 4.0.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Web.HttpUtility.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Threading.ThreadPool.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 4.1.1.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Reflection.Emit.Lightweight.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.700.20.51601
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Private.CoreLib.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 4.1.2.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 1.4.5.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 1.2.5.0
    Win32 Version: 4.700.20.51901
    CodeBase: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.10/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

`

**Comment by ishaanmeena** [comment]
Update : Happens with the latest release as well.

**Comment by RumbleMike** [comment]
you have to update, I broke all old version.

**Comment by ishaanmeena** [comment]
> you have to update, I broke all old version.

Still getting the same error.

**Comment by Whanos** [comment]
Did you fill in the required settings correctly?

**Comment by ishaanmeena** [comment]
> Did you fill in the required settings correctly?

Yes, I just tried to compile the source code on my system. Looks like it's the problem with the deserialization of the ranks...
