### ISSUE TITLE
Error when is opened from the windows bar desktop menu

### ISSUE THREAD

**Issue by ProxyJoshua** [RumbleMike/ValorantStreamOverlay#95]
![image](https://user-images.githubusercontent.com/56043504/103589923-4f423a00-4ecb-11eb-8983-4ca715019692.png)
When the program is opened from here throws an error.

My computer is in Spanish but I hope this can be useful btw.

```
Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.IO.FileNotFoundException: Unable to find the specified file.
   at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
   at ValorantStreamOverlay.ValorantOverStream.ValorantOverStream_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Ensamblados cargados **************
System.Private.CoreLib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.700.19.60701
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Private.CoreLib.dll
----------------------------------------
ValorantStreamOverlay
    Versión del ensamblado: 1.1.0.1
    Versión Win32: 1.1.0.0
    Código base: file:///C:/Users/PROXYJ~1/AppData/Local/Temp/.net/ValorantStreamOverlay/xwzsafpx.eir/ValorantStreamOverlay.dll
----------------------------------------
System.Runtime
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.800.119.60505
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Versión del ensamblado: 4.2.1.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Collections.Specialized.dll
----------------------------------------
System.Runtime.InteropServices
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Common
    Versión del ensamblado: 4.0.2.0
    Versión Win32: 4.700.19.56404
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Collections.dll
----------------------------------------
System.Runtime.Extensions
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Runtime.Extensions.dll
----------------------------------------
System.Diagnostics.Debug
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Diagnostics.Debug.dll
----------------------------------------
Microsoft.Win32.Primitives
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.800.119.60505
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/Accessibility.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Resources.ResourceManager
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Resources.ResourceManager.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Versión del ensamblado: 4.0.2.0
    Versión Win32: 4.700.19.56404
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Versión del ensamblado: 4.0.15.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Versión del ensamblado: 4.0.4.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.ComponentModel.dll
----------------------------------------
System.Collections.NonGeneric
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Collections.NonGeneric.dll
----------------------------------------
System.Memory
    Versión del ensamblado: 4.2.1.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Memory.dll
----------------------------------------
System.Resources.Extensions
    Versión del ensamblado: 4.0.1.0
    Versión Win32: 4.700.19.56404
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/System.Resources.Extensions.dll
----------------------------------------
netstandard
    Versión del ensamblado: 2.1.0.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/netstandard.dll
----------------------------------------
System.ObjectModel
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.ObjectModel.dll
----------------------------------------
System.Linq
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Linq.dll
----------------------------------------
System.Windows.Extensions
    Versión del ensamblado: 4.0.1.0
    Versión Win32: 4.700.19.56404
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/System.Windows.Extensions.dll
----------------------------------------
System.Buffers
    Versión del ensamblado: 4.0.5.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Buffers.dll
----------------------------------------
System.IO.FileSystem
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.IO.FileSystem.dll
----------------------------------------
AutoUpdater.NET
    Versión del ensamblado: 1.6.4.0
    Versión Win32: 1.6.4.0
    Código base: file:///C:/Users/PROXYJ~1/AppData/Local/Temp/.net/ValorantStreamOverlay/xwzsafpx.eir/AutoUpdater.NET.dll
----------------------------------------
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/mscorlib.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.800.119.60505
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/System.Drawing.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.dll
----------------------------------------
System.Net.ServicePoint
    Versión del ensamblado: 4.0.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.ServicePoint.dll
----------------------------------------
System.Net.Security
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.Security.dll
----------------------------------------
System.Net.WebClient
    Versión del ensamblado: 4.0.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.WebClient.dll
----------------------------------------
System.Net.Requests
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.Requests.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Xml.dll
----------------------------------------
System.Private.Xml
    Versión del ensamblado: 4.0.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Private.Xml.dll
----------------------------------------
System.Private.Uri
    Versión del ensamblado: 4.0.6.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Private.Uri.dll
----------------------------------------
System.Net.Primitives
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.Primitives.dll
----------------------------------------
System.Net.WebHeaderCollection
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Diagnostics.Tracing
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Diagnostics.Tracing.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.800.119.60505
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.WindowsDesktop.App/3.1.1/es/System.Windows.Forms.resources.dll
----------------------------------------
System.Security.Principal
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Security.Principal.dll
----------------------------------------
System.Net.Http
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Net.Http.dll
----------------------------------------
System.Diagnostics.StackTrace
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Versión del ensamblado: 1.4.5.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Versión del ensamblado: 1.2.5.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Collections.Immutable.dll
----------------------------------------
System.Text.RegularExpressions
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Text.RegularExpressions.dll
----------------------------------------
System.Threading.Tasks
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Threading.Tasks.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Versión del ensamblado: 4.2.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Versión del ensamblado: 4.1.2.0
    Versión Win32: 4.700.19.60801
    Código base: file:///C:/Program%20Files%20(x86)/dotnet/shared/Microsoft.NETCore.App/3.1.1/System.Security.Cryptography.Primitives.dll
----------------------------------------

************** Depuración JIT **************
```

**Comment by BobbyESP** [comment]
Tienes la última versión del programa? Porque Mike va destruyendo las versiones antiguas.
